services:

  app:
    build: .
    container_name: project_api_node
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shared_network

networks:
  shared_network:
    external: true
